### ISSUE TITLE
Is this the same as project-config?

### ISSUE THREAD

**Issue by UziTech** [arakilian0/dotatom#1]
Is this the same as [`project-config`](https://atom.io/packages/project-config)?

**Comment by arakilian0** [comment]
no It’s dotatom

**Comment by UziTech** [comment]
Yes I understand the package is different. Does it do the same thing as project-config?

**Comment by arakilian0** [comment]
I don’t know. What’s your point?

**Comment by UziTech** [comment]
Just wondering what the difference is between the two packages.

**Comment by UziTech** [comment]
other than the name

**Comment by UziTech** [comment]
and the file name used. (this one uses `settings.json`, that one uses `config.json`)

**Comment by arakilian0** [comment]
Well for starters dotatom isn’t working properly 😂

**Comment by arakilian0** [comment]
Yeah I don’t know about that package at all. Don’t really care for it.
